config/routes.rb
Hockey::Application.routes.draw do

  resources :contacts, :only => [:new, :create]

  namespace :feed do
    resources :user_posts, :only => [:create]
  end

  resources :feed_items, :only => [:index, :show]

  resources :followings, :only => [:create, :destroy]
  get 'followings' => "followings#create"

  resources :games, :only => [:show, :update]

  namespace :marker do
    resources :games, :only => :show do
      resources :goals, :only => [:index, :new, :create, :update, :destroy]
      resources :penalties, :only => [:create, :update, :destroy]
      resource :roster, :only => [:show, :new, :create, :edit, :update], :controller => "game_players"
      resources :game_goalies, :only => [:new, :create]
      resource :game_officials, :only => [:edit, :update]
      resource :game_staff_members, :only => [:new, :create, :edit, :update]
      member do
        post :activate
        post :start
        post :pause
        post :finish
        post :complete
        post :sync
        put :update_clock
        put :set_mvp
      end
    end
  end

  resources :locations, :except => [:destroy] do
    resource :scoreboard, :only => :show, :controller => "locations/scoreboards"
  end

  resources :players, :only => [:show, :edit, :update, :destroy] do
    resources :claims, :only => [:show, :new, :create], :controller => "players/claims" do
      member do
        post :approve
        post :deny
      end
    end
  end

  resources :search, :only => :index, :controller => "search_results"

  resources :shared_links, :only => [:new, :create]

  resources :teams, :only => [:index, :show, :edit, :update, :destroy], :controller => "leagues/teams" do
    resources :players, :only => [:new, :create]
    resources :staff_members
  end

  resources :leagues do
    resources :teams, :only => [:new, :create], :controller => "leagues/teams"
    resources :games, :only => [:new, :create, :edit, :update, :destroy], :controller => "leagues/games"
    resources :officials, :controller => "leagues/officials"
  end

  resources :invitations, :only => [:new, :create] do
    member do
      get :accept
      get :decline
    end
  end

  resources :system_names, :only => [:show]

  resources :team_claims, :only => [:create, :show] do
    resources :players, :only => [:edit, :update], :controller => "team_claims/players"
  end

  resources :tournaments do
    resources :games, :controller => "tournaments/games"
    resources :officials, :controller => "tournaments/officials"
    resource :teams, :only => [:edit, :update], :controller => "tournaments/teams"
  end

  devise_for :users, :controllers => {:registrations => "users/registrations" }

  resources :users, :only => [:show, :edit, :update] do
    member do
      get :impersonate
    end
    collection do
      post :system_name_available
      post :email_available
    end
  end

  resources :videos, :only => [:show]

  match 'typeahead/get_users' => 'typeahead#get_users'

  namespace :admin do
    resource :kiosk, :except => [:edit, :update]
  end

  root :to => 'home#index'
  get 'about' => 'home#about'
  get 'terms' => 'home#terms'
  get 'privacy' => 'home#privacy'
  get 'press' => 'home#press'
  get 'contact' => 'home#contact'
  get 'account_created' => 'home#account_created'
  get 'popular' => "home#popular"

  get 'unsubscribe/:user_id/:token/:category' => 'unsubscribe#unsubscribe'

  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#server_error'
  match '/500', :to => 'errors#server_error'

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_authorization_check

  def index
    if current_user
      current_user.update_attribute(:last_viewed_home_page_at, Time.now)
    end
  end

  def about
  end

  def terms
  end

  def privacy
  end

  def press
  end

  def contact
    redirect_to new_contact_path
  end

  def account_created
  end

  def popular
  end
end

app/views/home/_activity_feed.html.erb
<h2 class="page-header">Activity Feed</h2>

<%= form_for(ActivityFeedItem.new) do |f| %>
  <div class="field pull-left" style="margin-right: 10px;" >
    <%= f.text_field :message, :class => "span4", :placeholder => "Enter status message here..." %>
  </div>

  <div class="actions">
    <%= f.submit "Post", :class => "btn btn-primary" %>
  </div>
<% end %>

<table class="table">
  <tr>
    <th>Avatar</th>
    <th>Name</th>
    <th>Message</th>
    <th>When</th>
  </tr>

  <% ActivityFeedItem.for(current_user).each do |item| %>
    <tr>
      <td><%= image_tag(item.avatar_url(:thumbnail), :width => 50, :height => 50) %>
      <td><%= format_user_link(item.creator) %>
      <td><%= format_message_with_usernames(item.message).html_safe %></td>
      <td><span title="<%= item.created_at %>"><%= distance_of_time_in_words_to_now(item.created_at) %> ago</span></td>
    </tr>
  <% end %>
</table>

app/views/home/_authorizations.html.erb
<% @authorizations.each do |obj| %>
  <div class="well text-center">
    <h3><%= link_to(obj.name, obj) %></h3>
    <div><%= link_to(image_tag(obj.logo_url(:small)), obj) %></div>
  </div>
<% end %>

app/views/home/_games.html.erb
<% if games.without_deleted.any? %>
  <h3><%= Game.model_name.human.pluralize %></h3>
  <table class="games table table-hover">
    <tr>
      <th><%= Game.human_attribute_name(:start_time) %></th>
      <th></th>
      <th><%= Game.human_attribute_name(:visiting_team) %></th>
      <th></th>
      <th><%= Game.human_attribute_name(:home_team) %></th>
      <th></th>
      <th><%= Game.human_attribute_name(:period) %></th>
      <th>Location</th>
      <th></th>
    </tr>

    <% games.without_deleted.each do |game| %>
      <tr <%= "style='font-weight: bold;" if game.live? %> >
        <td><%= l game.start_time, :format => :game %></td>
        <td class="visitor-name"><%= format_team_link(game.visiting_team) %></td>
        <td><%= link_to(image_tag(game.visiting_team.logo_url(:thumbnail)), game.visiting_team) %></td>
        <td class="score">
          <%= link_to game do %>
            <% if game.scheduled? %>
              <i>vs</i>
            <% else %>
              <%= "#{game.visiting_team_score}&nbsp;-&nbsp;#{game.home_team_score}".html_safe %>
            <% end %>
          <% end %>
        </td>
        <td><%= link_to(image_tag(game.home_team.logo_url(:thumbnail)), game.home_team) %></td>
        <td><%= format_team_link(game.home_team) %></td>
        <td class="period"><%= game.period_text %></td>
        <td>
          <%= link_to game.location.name, game.location %>
          <%= link_to game.location.map_url, :target => "_blank" do %>
            <%= image_tag "google-maps-icon-blank.svg", :class => "map-icon", :target => "_blank" %>
          <% end %>
        </td>
        <td style="text-align: right;"><%= link_to t("games.see_game"), game, :class => "btn" %></td>
      </tr>
    <% end %>
  </table>
<% end %>

app/views/home/_invitations.html.erb
<% if Invitation.pending.for_user(current_user).any? %>
  <div class="invitations">
    <% Invitation.pending.for_user(current_user).each do |invitation| %>
      <div class="alert alert-info">
        <a class="close" href="#" data-dismiss="alert">&#215;</a>
        <%= invitation.creator.name %> has invited you to <%= invitation.predicate %> <%= invitation.target.name %>.
        <div class="btn-group" style="margin-left: 20px">
          <%= link_to "Accept", accept_invitation_path(invitation), :class => "btn btn-default btn-sm" %>
          <%= link_to "Decline", decline_invitation_path(invitation), :class => "btn btn-default btn-sm" %>
        </div>
      </div>
    <% end %>
  </div>
<% end %>

app/views/home/_logged_out.html.erb
<%= render :partial => "welcome" %>

<div class="vimeo-container">
  <iframe src="//player.vimeo.com/video/89355487" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
</div>

<div class="row">
  <div class="col-md-6">
    <div class="well">
      <%= render :partial => "mini_sign_up" %>
    </div>
  </div>
  <div class="col-md-6">
    <div class="well" style="min-height: 230px;" >
      <%= render :partial => "mini_sign_in" %>
    </div>
  </div>
</div>

app/views/home/_orientation.html.erb
<% unless current_user.players.any? || Following.where(:user_id => current_user.id).any? %>
  <h2><%= t(".header", :name => current_user.name) %></h2>
  <%= t(".message_html") %>
<% end %>

app/views/home/_players.html.erb
<% current_user.players.each do |player| %>
  <div class="col-xs-12 col-sm-6 col-md-4">
    <div class="player tile">
      <div class="pull-left"><%= link_to(image_tag(player.photo_url(:thumbnail)), player) %></div>
      <div class="meta">
        <p class="name"><%= link_to(player.name, player) %></p>
        <p><%= link_to("##{player.jersey_number} - #{player.team.name}", player) %></p>
      </div>
    </div>
  </div>
<% end %>

app/views/home/_tournaments.html.erb
<h3><%= Tournament.model_name.human.pluralize %></h3>

<% if tournaments.without_deleted.any? %>
  <table class="tournaments table table-hover">
    <tr>
      <th><%= League.human_attribute_name(:division) %></th>
      <th><%= League.human_attribute_name(:name) %></th>
      <th><%= SystemName.human_attribute_name(:name) %></th>
      <th><%= Tournament.human_attribute_name(:dates) %></th>
    </tr>

    <% tournaments.without_deleted.sort_by {|t| [t.division, t.classification, t.name]}.each do |tournament| %>
        <tr>
          <td class="division"><%= t(tournament.division, :scope => "league.divisions") %>
              <%= t(tournament.classification, :scope => "league.classifications") %></td>
          <td><%= link_to tournament.name, tournament %></td>
          <td><%= format_team_link(tournament) %></td>
          <td><%= l tournament.start_date if tournament.start_date %> - <%= l tournament.end_date if tournament.end_date %></td>
        </tr>
    <% end %>
  </table>
<% end %>

app/views/home/about.html.erb
<h1><%= t(".header") %></h1>

<div class="vimeo-container">
  <iframe src="//player.vimeo.com/video/89355487" frameborder="0" webkitallowfullscreen mozallowfullscreen allowfullscreen></iframe>
</div>

app/views/home/index.html.erb
<% title "BigShot: Your social network for amateur and recreational sports" %>
<% description "BigShot is your social network for amateur and recreational sports." %>

<% if current_user %>
  <%= render :partial => "logged_in" %>
<% else %>
  <%= render :partial => "logged_out" %>
<% end %>

app/views/home/popular.html.erb
<h1><%= t(".header") %></h1>

<div class="search-results">
  <% Following.popular.each do |following| %>
    <% obj = following.followable %>
    <% class_name = obj.class.name.downcase %>
    <% fans = following.follows.to_i %>

    <div class="row result <%= class_name %>">
      <div class="col-sm-8">
        <%= render :partial => "search_results/#{class_name}", :locals => { class_name.to_sym => obj } %>
      </div>
      <div class="col-sm-4 text-right">
        <span class="fan-count"><%= t(".fans", :count => fans) %></span>
        <%= render :partial => "follow_button", :locals => { :target => obj, :back_to => request.url } %>
      </div>
    </div>
  <% end %>
</div>

app/views/home/press.html.erb
<h1><%= t(".header") %></h1>

<p>Coming soon!</p>

<p>For press inquiries, contact <%= link_to "us here", "mailto:info@bigshot.io?subject=Press Inquiry" %>.</p>

app/views/home/privacy.html.erb
<h1><%= t(".header") %></h1>

<p>Coming soon!</p>

app/views/home/terms.html.erb
<h1><%= t(".header") %></h1>

<p>Coming soon!</p>