config/routes.rb
Hockey::Application.routes.draw do

  resources :contacts, :only => [:new, :create]

  namespace :feed do
    resources :user_posts, :only => [:create]
  end

  resources :feed_items, :only => [:index, :show]

  resources :followings, :only => [:create, :destroy]
  get 'followings' => "followings#create"

  resources :games, :only => [:show, :update]

  namespace :marker do
    resources :games, :only => :show do
      resources :goals, :only => [:index, :new, :create, :update, :destroy]
      resources :penalties, :only => [:create, :update, :destroy]
      resource :roster, :only => [:show, :new, :create, :edit, :update], :controller => "game_players"
      resources :game_goalies, :only => [:new, :create]
      resource :game_officials, :only => [:edit, :update]
      resource :game_staff_members, :only => [:new, :create, :edit, :update]
      member do
        post :activate
        post :start
        post :pause
        post :finish
        post :complete
        post :sync
        put :update_clock
        put :set_mvp
      end
    end
  end

  resources :locations, :except => [:destroy] do
    resource :scoreboard, :only => :show, :controller => "locations/scoreboards"
  end

  resources :players, :only => [:show, :edit, :update, :destroy] do
    resources :claims, :only => [:show, :new, :create], :controller => "players/claims" do
      member do
        post :approve
        post :deny
      end
    end
  end

  resources :search, :only => :index, :controller => "search_results"

  resources :shared_links, :only => [:new, :create]

  resources :teams, :only => [:index, :show, :edit, :update, :destroy], :controller => "leagues/teams" do
    resources :players, :only => [:new, :create]
    resources :staff_members
  end

  resources :leagues do
    resources :teams, :only => [:new, :create], :controller => "leagues/teams"
    resources :games, :only => [:new, :create, :edit, :update, :destroy], :controller => "leagues/games"
    resources :officials, :controller => "leagues/officials"
  end

  resources :invitations, :only => [:new, :create] do
    member do
      get :accept
      get :decline
    end
  end

  resources :system_names, :only => [:show]

  resources :team_claims, :only => [:create, :show] do
    resources :players, :only => [:edit, :update], :controller => "team_claims/players"
  end

  resources :tournaments do
    resources :games, :controller => "tournaments/games"
    resources :officials, :controller => "tournaments/officials"
    resource :teams, :only => [:edit, :update], :controller => "tournaments/teams"
  end

  devise_for :users, :controllers => {:registrations => "users/registrations" }

  resources :users, :only => [:show, :edit, :update] do
    member do
      get :impersonate
    end
    collection do
      post :system_name_available
      post :email_available
    end
  end

  resources :videos, :only => [:show]

  match 'typeahead/get_users' => 'typeahead#get_users'

  namespace :admin do
    resource :kiosk, :except => [:edit, :update]
  end

  root :to => 'home#index'
  get 'about' => 'home#about'
  get 'terms' => 'home#terms'
  get 'privacy' => 'home#privacy'
  get 'press' => 'home#press'
  get 'contact' => 'home#contact'
  get 'account_created' => 'home#account_created'
  get 'popular' => "home#popular"

  get 'unsubscribe/:user_id/:token/:category' => 'unsubscribe#unsubscribe'

  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#server_error'
  match '/500', :to => 'errors#server_error'

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end
end

app/models/league.rb
class League < ActiveRecord::Base
  include SoftDelete
  include Followable
  include PgSearch

  Divisions = %w(prenovice initiation novice atom pee_wee bantam midget intermediate juvenile secondary junior major_junior other_junior adult_recreational senior college university house).map(&:to_sym)
  Classifications = %w(a b c aa bb cc aaa).map(&:to_sym)

  has_many :games, :dependent => :destroy, :conditions => { deleted_at: nil }
  has_many :teams, :dependent => :destroy, :conditions => { deleted_at: nil }
  has_many :officials, :conditions => { deleted_at: nil }
  has_many :authorizations, :as => :authorizable, :dependent => :destroy
  has_many :mentions, :as => :mentionable
  has_many :activity_feed_items, :through => :mentions
  attr_accessible :name, :logo, :logo_cache, :division, :classification
  symbolize :classification, :in => Classifications, :allow_nil => true
  symbolize :division, :in => Divisions

  scope :managed_by, lambda {|user| joins(:authorizations).where(:authorizations => {:user_id => user.id, :role => :manager }) }

  validates_presence_of :name
  validates_uniqueness_of :name, :scope => [:classification, :division]

  mount_uploader :logo, LogoUploader

  strip_attributes

  multisearchable :against => [:name, :classification, :division]

  def managers
    User.joins(:authorizations).where(:authorizations => {:role => :manager, :authorizable_type => self.class.base_class, :authorizable_id => self.id})
  end

  def markers
    User.joins(:authorizations).where(:authorizations => {:role => :marker, :authorizable_type => self.class, :authorizable_id => self.id})
  end

  def accepted_invitation_to_manage(user, invitation)
    League.transaction do
      begin
        Authorization.create!(:user => user, :role => :manager, :authorizable => self)
        Feed::NewLeagueManager.create!(:user => user, :league => self)
      rescue ActiveRecord::RecordInvalid => e
        # If the authorization already exists, fail silently
        raise unless e.message == "Validation failed: User has already been taken"
      end
    end
  end

  def declined_invitation_to_manage(user, invitation)
    # Whatevs
  end

  def accepted_invitation_to_mark(user, invitation)
    League.transaction do
      begin
        Authorization.create!(:user => user, :role => :marker, :authorizable => self)
        Feed::NewLeagueMarker.create!(:user => user, :league => self)
      rescue ActiveRecord::RecordInvalid => e
        # If the authorization already exists, fail silently
        raise unless e.message == "Validation failed: User has already been taken"
      end
    end
  end

  def declined_invitation_to_manage(user, invitation)
    # Whatevs
  end
end

app/controllers/leagues/games_controller.rb
class Leagues::GamesController < ApplicationController
  load_and_authorize_resource :league, :only => [:new, :create, :edit, :update]
  load_and_authorize_resource :except => [:new, :create]

  def new
    @game = @league.games.build
    authorize! :new, @game
  end

  def create
    @game = @league.games.build(params[:game].merge(:updater => current_user))
    authorize! :create, @game

    respond_to do |format|
      if @game.save
        format.html { redirect_to league_path(@league), notice: t("controllers.leagues.games.create.success") }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @game.update_attributes(params[:game].merge(:updater => current_user))
        format.html { redirect_to @league, notice: t("controllers.leagues.games.update.success") }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      @game.updater = current_user
      if @game.cancel
        format.html { redirect_to :back, notice: t("controllers.leagues.games.destroy.success") }
        format.json { head :no_content }
      else
        format.html { redirect_to :back, alert: t("controllers.leagues.games.destroy.failure") }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/leagues/officials_controller.rb
class Leagues::OfficialsController < ApplicationController
  load_and_authorize_resource :league
  load_and_authorize_resource :except => [:new, :create]

  def show
  end

  def new
    @official = Official.new
  end

  def create
    @official = @league.officials.build(params[:official])

    respond_to do |wants|
      if @official.save
        flash[:notice] = t("controllers.leagues.officials.create.success")
        wants.html { redirect_to(@league) }
        wants.xml  { render :xml => @official, :status => :created, :location => @league }
      else
        wants.html { render :action => "new" }
        wants.xml  { render :xml => @official.errors, :status => :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |wants|
      if @official.update_attributes(params[:official])
        flash[:notice] = t("controllers.leagues.officials.update.success")
        wants.html { redirect_to(@league) }
        wants.xml  { head :ok }
      else
        wants.html { render :action => "edit" }
        wants.xml  { render :xml => @official.errors, :status => :unprocessable_entity }
      end
    end
  end

  def destroy
    @official.destroy

    respond_to do |wants|
      flash[:notice] = t("controllers.leagues.officials.destroy.success")
      wants.html { redirect_to(@league) }
      wants.xml  { head :ok }
    end
  end
end

app/controllers/leagues/teams_controller.rb
class Leagues::TeamsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  load_and_authorize_resource :league, :only => [:new, :create]
  load_and_authorize_resource

  # GET /teams
  # GET /teams.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teams }
    end
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
    raise ActiveRecord::RecordNotFound if @team.deleted_at
    @league = @team.league
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @team }
    end
  end

  # GET /teams/new
  # GET /teams/new.json
  def new
    @team = Team.new
    @team.build_system_name

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @team }
    end
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /leagues/1/teams
  # POST /leagues/1/teams.json
  def create
    @team = Team.new(params[:team].merge(:manager => current_user, :league => @league))

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: t("controllers.leagues.teams.create.success") }
        format.json { render json: @team, status: :created, location: @team }
      else
        format.html { render action: "new" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teams/1
  # PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update_attributes(params[:team])
        format.html { redirect_to @team, notice: t("controllers.leagues.teams.update.success") }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy

    respond_to do |format|
      format.html { redirect_to @team.league, notice: t("controllers.leagues.teams.destroy.success") }
      format.json { head :no_content }
    end
  end
end

app/controllers/leagues_controller.rb
class LeaguesController < ApplicationController
  load_and_authorize_resource

  # GET /leagues
  # GET /leagues.json
  def index
    @leagues = League.where(:type => [nil, "League"])

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @leagues }
    end
  end

  # GET /leagues/1
  # GET /leagues/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @league }
    end
  end

  # GET /leagues/new
  # GET /leagues/new.json
  def new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @league }
    end
  end

  # GET /leagues/1/edit
  def edit
  end

  # POST /leagues
  # POST /leagues.json
  def create
    @league = League.new(params[:league])

    respond_to do |format|
      if @league.save
        format.html { redirect_to @league, notice: t("controllers.leagues.create.success") }
        format.json { render json: @league, status: :created, location: @league }
      else
        format.html { render action: "new" }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /leagues/1
  # PUT /leagues/1.json
  def update
    respond_to do |format|
      if @league.update_attributes(params[:league])
        format.html { redirect_to @league, notice: t("controllers.leagues.update.success") }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @league.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leagues/1
  # DELETE /leagues/1.json
  def destroy
    @league.destroy

    respond_to do |format|
      format.html { redirect_to leagues_url, notice: t("controllers.leagues.destroy.success") }
      format.json { head :no_content }
    end
  end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_filter :authenticate_user!, :except => [:index, :show]
  load_and_authorize_resource :league, :only => [:new, :create]
  load_and_authorize_resource

  # GET /teams
  # GET /teams.json
  def index
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @teams }
    end
  end

  # GET /teams/1
  # GET /teams/1.json
  def show
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @team }
    end
  end

  # GET /teams/new
  # GET /teams/new.json
  def new
    @team = Team.new
    @team.build_system_name

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @team }
    end
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /leagues/1/teams
  # POST /leagues/1/teams.json
  def create
    @team = Team.new(params[:team].merge(:manager => current_user, :league => @league))

    respond_to do |format|
      if @team.save
        format.html { redirect_to @team, notice: 'Team was successfully created.' }
        format.json { render json: @team, status: :created, location: @team }
      else
        format.html { render action: "new" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /teams/1
  # PUT /teams/1.json
  def update
    respond_to do |format|
      if @team.update_attributes(params[:team])
        format.html { redirect_to @team, notice: 'Team was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1
  # DELETE /teams/1.json
  def destroy
    @team.destroy

    respond_to do |format|
      format.html { redirect_to teams_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/tournaments/teams_controller.rb
class Tournaments::TeamsController < ApplicationController
  load_and_authorize_resource :tournament

  def edit
  end

  def update
    respond_to do |format|
      if @tournament.update_attributes(params[:tournament])
        format.html { redirect_to @tournament, notice: t("controllers.tournaments.teams.update") }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tournament.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/helpers/leagues_helper.rb
module LeaguesHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/leagues/teams/_form.html.erb
<%= form_for([@league, @team]) do |f| %>
  <% if @team.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@team.errors.count, "error") %> prohibited this team from being saved:</h2>

      <ul>
      <% @team.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :"data-suggest-system-name-in" => "team_system_name_attributes_name", :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :city %>
    <%= f.text_field :city, :class => "form-control" %>
  </div>

  <%= f.fields_for :system_name do |snf| %>
    <div class="form-group">
      <%= snf.label :name %>
      <div class="input-group">
        <span class="input-group-addon">@</span>
        <%= snf.text_field :name, :class => "form-control" %>
      </div>
    </div>
  <% end %>

  <%= f.hidden_field :logo_cache %>

  <div class="form-group">
    <% if @team.logo.present? %>
      <%= cl_image_tag @team.logo_url(:thumbnail), :height => 50, :width => 50, :style => "float: left; margin-right: 10px" %>
    <% end %>

    <%= f.label :logo %>
    <%= f.file_field :logo %>
  </div>

  <%= f.hidden_field :alpha_logo_cache %>

  <div class="form-group">
    <% if @team.alpha_logo.present? %>
      <%= cl_image_tag @team.alpha_logo_url(:thumbnail), :height => 50, :width => 50, :style => "float: left; margin-right: 10px" %>
    <% end %>

    <%= f.label :alpha_logo %>
    <%= f.file_field :alpha_logo %>
  </div>

  <div class="actions">
    <%= f.submit :class => "btn btn-primary" %>
  </div>
<% end %>

app/views/leagues/teams/_players.html.erb
<p class="text-right">
  <%= link_to t("team.add_player"), new_team_player_path(@team), :class => "btn btn-default" if can? :create, Player.new(:team => @team) %>
  <%= link_to(t(".get_private_link"), team_claims_path(:team_claim => {:team_id => @team.to_param}), :class => "btn btn-default", :method => :post) if can?(:create, TeamClaim.new(:team => @team)) %>
</p>
<p><%= t(".no_players") unless players.any? %></p>

<div>
  <% players.each do |player| %>
    <div class="player">
      <div class="photo">
        <%= link_to(image_tag(player.photo_url(:small_face)), player) %>
        <div class="jersey">#<%= player.jersey_number %></div>
      </div>
      <%= link_to(player.name, player, :class => "name") %>
      <% if player.user %>
        <%= link_to(player.user.at_name, player, :class => "at_name") %>
      <% else %>
        <div class="at_name"></div>
      <% end %>
      <% if current_user %>
        <div><%= render :partial => "follow_button", :locals => {:target => player, :back_to => request.url, :button_size => "xs" } %></div>
      <% end %>
      <% if can?(:edit, player) || can?(:delete, player) %>
        <div class="dropdown btn btn-default btn-xs">
          <%= link_to raw('<span class="glyphicon glyphicon-cog"><b class="caret"></b>'), "#", :data => {:toggle => "dropdown" } %>
          <ul class="dropdown-menu dropdown-menu-right">
            <li><%= link_to t("actions.edit"), edit_player_path(player) if can? :edit, player %></li>
            <li><%= link_to t("actions.remove"), player, method: :delete, data: { confirm: t("actions.confirm") } if can? :delete, player %></li>
          </ul>
        </div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/leagues/teams/_staff_members.html.erb
<ul>
  <% @team.managers.order(:name).each do |manager| %>
    <li><%= manager.name %> (<%= format_user_link(manager) %>, <%= t("activerecord.values.authorization.role.manager") %>)</li>
  <% end %>
  <% @team.staff_members.sort_by {|sm| StaffMember::Roles.index(sm.role) || 0}.each do |sm| %>
    <% unless sm.role == :manager && @team.managers.map(&:name).include?(sm.name) %>
      <li><%= sm.name_and_role %></li>
    <% end %>
  <% end %>
</ul>

<%= link_to t("actions.edit"), team_staff_members_path(@team), :class => "btn btn-default btn-sm" if can? :update, @team %>
<%= invitation_button(:manage, @team) %>

app/views/leagues/teams/edit.html.erb
<h1>Editing team</h1>

<%= render 'form' %>

<%= link_to 'Show', @team %> |
<%= link_to 'Back', @team.league %>

app/views/leagues/teams/index.html.erb
<h1>Listing teams</h1>

<table class="table table-hover">
  <tr>
    <th style="width: 50px;">Logo</th>
    <th>City</th>
    <th>Name</th>
    <th>Profile</th>
    <th></th>
    <th>League</th>
    <th></th>
    <th></th>
  </tr>

<% @teams.without_deleted.each do |team| %>
  <tr>
    <td><%= cl_image_tag(team.logo_url(:thumbnail), :width => 50, :height => 50) if team.logo.present? %>
    <td><%= team.city %></td>
    <td><%= link_to team.name, team %></td>
    <td>
      <%= format_team_link(team) %>
      <%= render :partial => 'follow_button', :locals => {:target => team } %>
    </td>
    <td><%= team.league.name %></td>
    <td><%= link_to 'Edit', edit_team_path(team) %></td>
  </tr>
<% end %>
</table>

app/views/leagues/teams/new.html.erb
<h1>New team</h1>

<%= render 'form' %>

<%= link_to 'Back', league_path(@league) %>

app/views/leagues/teams/show.html.erb
<% title [@team.name, @team.city, @team.league.name].compact.join(" - ") %>

<div class="row team-meta">
  <div class="col-xs-12 col-sm-4 photo">
    <%= image_tag(@team.alpha_logo_url(:medium), :alt => "#{@team.name} Logo") %>
  </div>
  <div class="col-xs-12 col-sm-5 team-name">
    <h1>
      <%= @team.name %>
      <small style="white-space: nowrap;">
        <%= t(@team.division, :scope => "league.divisions") %>
        <%= t(@team.classification, :scope => "league.classifications") if @team.classification.present? %>
      </small>
    </h1>
    <h2><%= @team.city %></h2>
    <%= format_team_link(@team) %>
    <h3>
      <%= link_to(@league.name, @league) %>
    </h3>
  </div>
  <div class="col-xs-12 col-sm-3 buttons">
    <div class="text-right">
      <%= render partial: "follow_button", locals: { target: @team } %>
      <%= link_to t("actions.edit"), edit_team_path(@team), :class => "btn btn-default btn-sm" if can?(:edit, @team) %>
      <p></p>
    </div>
  </div>
</div>

<hr>

<%= javascript_tag do %>
  $(function() {
    $(".nav-tabs a").click(function(e) {
      e.preventDefault();
      $(this).tab("show");
    });
    $(".nav-tabs a:first").tab("show");
  });
<% end %>

<div class="row main">
  <div class="col-xs-12">

    <ul class="nav nav-tabs">
      <li><%= link_to ActivityFeedItem.model_name.human.pluralize, "#feed", :data => {:toggle => "tab" } %></li>
      <li><%= link_to Player.model_name.human.pluralize, "#players", :data => {:toggle => "tab" } %></li>
      <li><%= link_to Game.model_name.human.pluralize, "#games", :data => {:toggle => "tab" } %></li>
      <li><%= link_to "#fans", :data => {:toggle => "tab" } do %>
        <%= t("header", :scope => "followers", :name => @team.name) %>
          <span class="badge"><%= @team.followers.count %></span>
        <% end %>
      </li>
      <li><%= link_to t(".staff_members"), "#staff", :data => {:toggle => "tab" } %></li>
      <li>
        <%= link_to "#videos", :data => {:toggle => "tab" } do %>
          <span class="glyphicon glyphicon-facetime-video"></span>
        <% end %>
      </li>
    </ul>

    <div class="tab-content">
      <div class="tab-pane active fade" id="feed">
        <%= render :partial => "activity_feed", :locals => { :context => @team, :hide_header => true } %>
      </div>
      <div class="tab-pane fade" id="players">
        <%= render :partial => "players", :locals => { :players => @team.players } %>
      </div>
      <div class="tab-pane fade" id="games">
        <%= render :partial => "games", :locals => { :games => Game.for_team(@team), :compact => true, :hide_header => true } %>
      </div>
      <div class="tab-pane fade" id="fans">
        <%= render :partial => "followers", :locals => {:target => @team, :hide_header => true } %>
      </div>
      <div class="tab-pane fade" id="staff">
        <%= render :partial => "staff_members" %>
      </div>
      <div class="tab-pane fade" id="videos">
        <%= render :partial => "videos", :locals => {:target => @team } %>
      </div>
    </div>

  </div>
</div>
<p><br><%= link_to t("navigation.back_html"), root_path %></p>