config/routes.rb
Hockey::Application.routes.draw do

  resources :contacts, :only => [:new, :create]

  namespace :feed do
    resources :user_posts, :only => [:create]
  end

  resources :feed_items, :only => [:index, :show]

  resources :followings, :only => [:create, :destroy]
  get 'followings' => "followings#create"

  resources :games, :only => [:show, :update]

  namespace :marker do
    resources :games, :only => :show do
      resources :goals, :only => [:index, :new, :create, :update, :destroy]
      resources :penalties, :only => [:create, :update, :destroy]
      resource :roster, :only => [:show, :new, :create, :edit, :update], :controller => "game_players"
      resources :game_goalies, :only => [:new, :create]
      resource :game_officials, :only => [:edit, :update]
      resource :game_staff_members, :only => [:new, :create, :edit, :update]
      member do
        post :activate
        post :start
        post :pause
        post :finish
        post :complete
        post :sync
        put :update_clock
        put :set_mvp
      end
    end
  end

  resources :locations, :except => [:destroy] do
    resource :scoreboard, :only => :show, :controller => "locations/scoreboards"
  end

  resources :players, :only => [:show, :edit, :update, :destroy] do
    resources :claims, :only => [:show, :new, :create], :controller => "players/claims" do
      member do
        post :approve
        post :deny
      end
    end
  end

  resources :search, :only => :index, :controller => "search_results"

  resources :shared_links, :only => [:new, :create]

  resources :teams, :only => [:index, :show, :edit, :update, :destroy], :controller => "leagues/teams" do
    resources :players, :only => [:new, :create]
    resources :staff_members
  end

  resources :leagues do
    resources :teams, :only => [:new, :create], :controller => "leagues/teams"
    resources :games, :only => [:new, :create, :edit, :update, :destroy], :controller => "leagues/games"
    resources :officials, :controller => "leagues/officials"
  end

  resources :invitations, :only => [:new, :create] do
    member do
      get :accept
      get :decline
    end
  end

  resources :system_names, :only => [:show]

  resources :team_claims, :only => [:create, :show] do
    resources :players, :only => [:edit, :update], :controller => "team_claims/players"
  end

  resources :tournaments do
    resources :games, :controller => "tournaments/games"
    resources :officials, :controller => "tournaments/officials"
    resource :teams, :only => [:edit, :update], :controller => "tournaments/teams"
  end

  devise_for :users, :controllers => {:registrations => "users/registrations" }

  resources :users, :only => [:show, :edit, :update] do
    member do
      get :impersonate
    end
    collection do
      post :system_name_available
      post :email_available
    end
  end

  resources :videos, :only => [:show]

  match 'typeahead/get_users' => 'typeahead#get_users'

  namespace :admin do
    resource :kiosk, :except => [:edit, :update]
  end

  root :to => 'home#index'
  get 'about' => 'home#about'
  get 'terms' => 'home#terms'
  get 'privacy' => 'home#privacy'
  get 'press' => 'home#press'
  get 'contact' => 'home#contact'
  get 'account_created' => 'home#account_created'
  get 'popular' => "home#popular"

  get 'unsubscribe/:user_id/:token/:category' => 'unsubscribe#unsubscribe'

  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#server_error'
  match '/500', :to => 'errors#server_error'

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end
end

app/controllers/game_players_controller.rb
class GamePlayersController < ApplicationController
  load_and_authorize_resource :game
  before_filter :load_home_or_visiting
  before_filter :load_team

  # There's probably a better pattern than what we're doing here.
  # #new and #create support the creation of new players. #edit and #update manage
  # the game roster.

  def show
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
    end
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(params[:player].merge(:team => @team))

    respond_to do |format|
      if @player.save && @game.players << @player
        format.html { redirect_to edit_game_roster_path(@game, :team => @home_or_visiting), notice: 'Player was successfully added.' }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    render :layout => false if request.xhr?
  end

  def update
    respond_to do |format|
      if @game.update_attributes(fix_params[:game])
        format.html { redirect_to @game, notice: 'Game roster was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def fix_params
    return params unless params[:game] && params[:game][:game_players_attributes]
    # First, get rid of entries for which we haven't persisted anything and which haven't been selected
    params[:game][:game_players_attributes].delete_if { |k, v| !v[:id] && !v[:selected] }

    # Then, add the "_destroy" directive to anything that remains and is unselected
    params[:game][:game_players_attributes].each do |k, v|
      v[:_destroy] = true unless v[:selected]
      v.delete(:selected)
    end

    # Leave untouched anything that is selected -- they'll be created or updated as appropriate
    params
  end

  def load_home_or_visiting
    @home_or_visiting = params[:team] == "visiting" ? "visiting" : "home"
  end

  def load_team
    @team = @game.send("#{@home_or_visiting}_team")
    @other_team = @game.opposing_team(@team)
  end
end

app/controllers/marker/game_goalies_controller.rb
class Marker::GameGoaliesController < ApplicationController
  load_and_authorize_resource :game
  before_filter :load_team

  def new
    @game_goalie = @game.game_goalies.build
    authorize! :create, @game_goalie
    render :layout => !request.xhr?
  end

  def create
    @game_goalie = @game.game_goalies.build(params[:game_goalie])
    authorize! :create, @game_goalie

    if @game_goalie.goalie_id == 0
      @game.game_goalies.for_team(@team).current.readonly(false).each {|gg| gg.finish! }
      respond_to do |format|
        format.html { redirect_to @game, notice: t("controllers.marker.game_goalies.pulled") }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        if @game_goalie.save
          format.html { redirect_to @game, notice: t("controllers.marker.game_goalies.changed") }
          format.json { render json: @game, status: :created, location: @game }
        else
          format.html { render action: "new" }
          format.json { render json: @game_goalie.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  private

  def load_team
    @team = params[:team] == "visiting" ? @game.visiting_team : @game.home_team
  end
end

app/controllers/marker/game_officials_controller.rb
class Marker::GameOfficialsController < ApplicationController
  load_and_authorize_resource :game
  before_filter :load_game_officials

  def edit
    authorize! :edit, GameOfficial.new(:game => @game)
  end

  def update
    authorize! :edit, GameOfficial.new(:game => @game)

    respond_to do |format|
      begin
        if @game.update_attributes(params[:game])
          format.html { redirect_to marker_game_path(@game), notice: t("controllers.marker.game_officials.update.success") }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @game.errors, status: :unprocessable_entity }
        end
      rescue ActiveRecord::RecordInvalid => e
        @game.errors.add(:base, t("controllers.marker.game_officials.update.failure") )
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def load_game_officials
    @game_officials = @game.possible_officials.map {|o| [o.name, o.id] }
  end
end

app/controllers/marker/game_players_controller.rb
class Marker::GamePlayersController < ApplicationController
  load_and_authorize_resource :game
  before_filter :load_home_or_visiting
  before_filter :load_team

  # There's probably a better pattern than what we're doing here.
  # #new and #create support the creation of new players. #edit and #update manage
  # the game roster.

  def show
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
    end
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(params[:player].merge(:team => @team))

    respond_to do |format|
      if @player.save && @game.players << @player
        format.html { redirect_to edit_marker_game_roster_path(@game, :team => @home_or_visiting), notice: t("controllers.marker.game_players.create.success") }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    render :layout => false if request.xhr?
  end

  def update
    respond_to do |format|
      if @game.update_attributes(fix_params[:game])
        format.html { redirect_to marker_game_path(@game), notice: t("controllers.marker.game_players.update.success") }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def fix_params
    return params unless params[:game] && params[:game][:game_players_attributes]
    # First, get rid of entries for which we haven't persisted anything and which haven't been selected
    params[:game][:game_players_attributes].delete_if { |k, v| !v[:id] && !v[:selected] }

    # Then, add the "_destroy" directive to anything that remains and is unselected
    params[:game][:game_players_attributes].each do |k, v|
      v[:_destroy] = true unless v[:selected]
      v.delete(:selected)
    end

    # Leave untouched anything that is selected -- they'll be created or updated as appropriate
    params
  end

  def load_home_or_visiting
    @home_or_visiting = params[:team] == "visiting" ? "visiting" : "home"
  end

  def load_team
    @team = @game.send("#{@home_or_visiting}_team")
    @other_team = @game.opposing_team(@team)
  end
end

app/controllers/marker/game_staff_members_controller.rb
class Marker::GameStaffMembersController < ApplicationController
  load_and_authorize_resource :game
  before_filter :load_home_or_visiting
  before_filter :load_team
  before_filter :load_and_authorize_staff_member, :only => [:new, :create]
  before_filter :authorize_game_staff_member, :only => [:edit, :update]

  def new
  end

  def create
    game_staff_member = @game.game_staff_members.build(:role => @staff_member.role, :staff_member => @staff_member)
    respond_to do |format|
      if game_staff_member.save
        format.html { redirect_to marker_game_path(@game), notice: t("controllers.marker.game_staff_members.create.success") }
        format.json { render json: @staff_member, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @staff_member.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @game.update_attributes(fix_params[:game])
        format.html { redirect_to marker_game_path(@game), notice: t("controllers.marker.game_staff_members.update.success") }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def authorize_game_staff_member
    authorize! :create, GameStaffMember.new(:game => @game)
  end

  def load_and_authorize_staff_member
    @staff_member = @team.staff_members.build(params[:staff_member])
    authorize! :create, @staff_member
  end

  def fix_params
    return params unless params[:game] && params[:game][:game_staff_members_attributes]
    # First, get rid of entries for which we haven't persisted anything and which haven't been selected
    params[:game][:game_staff_members_attributes].delete_if { |k, v| !v[:id] && !v[:selected] }

    # Then, add the "_destroy" directive to anything that remains and is unselected
    params[:game][:game_staff_members_attributes].each do |k, v|
      v[:_destroy] = true unless v[:selected]
      v.delete(:selected)
    end

    # Leave untouched anything that is selected -- they'll be created or updated as appropriate
    params
  end

  def load_home_or_visiting
    @home_or_visiting = params[:team] == "visiting" ? "visiting" : "home"
  end

  def load_team
    @team = @game.send("#{@home_or_visiting}_team")
    @other_team = @game.opposing_team(@team)
  end
end

app/controllers/marker/games_controller.rb
class Marker::GamesController < ApplicationController
  load_and_authorize_resource :league, :only => [:new, :create, :edit, :update]
  load_and_authorize_resource :except => [:new, :create]

  def show
  end

  def start
    respond_to do |format|
      if @game.start
        format.html { redirect_to :back, notice: 'Game has been started.' }
        format.json { head :no_content }
      else
        format.html { redirect_to :back, alert: 'Something went wrong.' }
        format.json { render json: ["Something went wrong."], status: :unprocessable_entity }
      end
    end
  end

  def pause
    respond_to do |format|
      if @game.pause_with_elapsed_time(params[:elapsed_time])
        format.html { redirect_to :back, notice: 'Game clock has been stopped.' }
        format.json { head :no_content }
      else
        format.html { redirect_to :back, alert: 'Something went wrong.' }
        format.json { render json: ["Something went wrong."], status: :unprocessable_entity }
      end
    end
  end

  def finish
    respond_to do |format|
      if @game.finish
        format.html { redirect_to :back, notice: 'The game has been ended.' }
        format.json { head :no_content }
      else
        format.html { redirect_to :back, alert: 'Something went wrong.' }
        format.json { render json: ["Something went wrong."], status: :unprocessable_entity }
      end
    end
  end

  def activate
    @game.marker = current_user
    respond_to do |format|
      if @game.activate
        format.html { redirect_to :back, notice: 'Game has been activated.' }
        format.json { head :no_content }
      else
        format.html { redirect_to :back, alert: 'Something went wrong.' }
        format.json { render json: ["Something went wrong."], status: :unprocessable_entity }
      end
    end
  end

  def complete
    respond_to do |format|
      if @game.complete
        format.html { redirect_to :back, notice: 'Game has been completed.' }
        format.json { head :no_content }
      else
        format.html { redirect_to :back, alert: 'Something went wrong.' }
        format.json { render json: ["Something went wrong."], status: :unprocessable_entity }
      end
    end
  end

  def sync
    respond_to do |format|
      if @game.sync
        format.html { redirect_to :back, notice: 'Game has been synced. Thanks.' }
        format.json { head :no_content }
      else
        format.html { redirect_to :back, alert: 'Something went wrong.' }
        format.json { render json: ["Something went wrong."], status: :unprocessable_entity }
      end
    end
  end

  AcceptableUpdateClockKeys = ["current_period_duration"]

  def update_clock
    respond_to do |format|
      if @game.update_attributes(params[:game].select {|key, val| AcceptableUpdateClockKeys.include?(key) })
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def set_mvp
    player_id = params[:game] && params[:game][:mvp_player_id].try(:to_i)
    if player_id && @game.game_players.map(&:player_id).include?(player_id)
      player = Player.find(player_id)
      team = player.team
      if team == @game.home_team
        @game.home_team_mvp = player
      else
        @game.visiting_team_mvp = player
      end
    end

    respond_to do |format|
      if @game.save
        @game.broadcast_changes
        format.html { redirect_to @game, notice: 'Game MVP was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/views/marker/game_players/edit.html.erb
<% unless request.xhr? %>
  <%= javascript_tag do %>
    $(function() {
      function toggleSelectVisibility(e) {
        var checked = $(this).is(":checked");
        $("select", $(e.target).parents("tr")).css({visibility: (checked ? "visible" : "hidden")});
        $("input[type=text]", $(e.target).parents("tr")).css({visibility: (checked ? "visible": "hidden")});
      }

      $(".players input[type=checkbox]").on("click", toggleSelectVisibility);
    });
  <% end %>
<% end %>
<% unless request.xhr? %>
  <h3>Which players from <%= @team.name %> are playing in this game?</h3>
<% end %>

<%= form_for(@game, :url => marker_game_roster_path(@game, :team => @home_or_visiting), :remote => request.xhr?) do |f| %>

  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited your update from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <table class="players">
    <% @team.players.each do |player| %>
      <tr>
        <% game_player = @game.game_players.where(:player_id => player.id).first %>
        <% if game_player %>
          <input name="game[game_players_attributes][<%= player.id %>][id]" value="<%= game_player.id %>" type="hidden" />
        <% end %>
        <input name="game[game_players_attributes][<%= player.id %>][player_id]" value="<%= player.id %>" type="hidden" />
        <td>
          <div class="checkbox">
            <%= label_tag "player_#{player.id}" do %>
              <%= check_box_tag "game[game_players_attributes[#{player.id}][selected]", true, game_player.present?, :id => "player_#{player.id}" %>
              <%= player.name_and_number %>
            <% end %>
          </div>
        </td>
        <td>
          <%= select_tag "game[game_players_attributes][#{player.id}][role]",
            options_for_select(Player::Roles.map {|r| [r.to_s.humanize, r]}, game_player.try(:role) || player.role),
            :style => "visibility: #{game_player ? 'visible' : 'hidden'}" %>
        </td>
        <td>
          <%= text_field_tag "game[game_players_attributes][#{player.id}][player_attributes][jersey_number]", player.jersey_number, :style => "visibility: #{game_player ? 'visible' : 'hidden'}; margin-left: 8px;" %>
          <%= hidden_field_tag "game[game_players_attributes][#{player.id}][player_attributes][id]", player.id %>
        </td>
      </tr>
    <% end %>
  </table>

  <% unless request.xhr? %>
    <%= f.submit "Update Game Roster", :class => "btn btn-primary" %>
  <% end %>

<% end %>

<% unless request.xhr? %>
  <div>
    <%= link_to "Add new player", new_marker_game_roster_path(@game, :team => @home_or_visiting) %>
  </div>
  <div>
    <%= link_to t("navigation.back_html"), marker_game_path(@game) %>
  </div>
<% end %>

app/views/marker/game_players/new.html.erb
<h2>Add player to <%= @team.name %></h2>

<%= form_for @player, :url => marker_game_roster_path(@game, :team => @home_or_visiting) do |f| %>
  <% if @player.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@player.errors.count, "error") %> prohibited this player from being create:</h2>

      <ul>
      <% @player.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %>
    <%= f.text_field :name, :class => "form-control" %>
  </div>

  <div class="form-group">
    <%= f.label :jersey_number %>
    <%= f.text_field :jersey_number, :class => "form-control col-md-2" %>
  </div>

  <div class="form-group">
    <%= f.label :role %>
    <%= f.collection_select :role, Player::Roles.map {|r| [r, r.to_s.humanize]}, :first, :second %>
  </div>

  <div class="form-group">
    <%= f.label :username_or_email, "Username or email (optional)" %>
    <%= f.text_field :username_or_email, :class => "form-control" %>
  </div>

  <%= f.submit "Add Player", :class => "btn btn-primary" %>
  <%= link_to "Back", edit_marker_game_roster_path(@game, :team => @home_or_visiting) %>
<% end %>

app/views/marker/game_players/show.html.erb
<ul>
  <% @game.players.each do |player| %>
    <li>
      <%= player.name_and_number %>
    </li>
  <% end %>
</ul>