config/routes.rb
Hockey::Application.routes.draw do

  resources :contacts, :only => [:new, :create]

  namespace :feed do
    resources :user_posts, :only => [:create]
  end

  resources :feed_items, :only => [:index, :show]

  resources :followings, :only => [:create, :destroy]
  get 'followings' => "followings#create"

  resources :games, :only => [:show, :update]

  namespace :marker do
    resources :games, :only => :show do
      resources :goals, :only => [:index, :new, :create, :update, :destroy]
      resources :penalties, :only => [:create, :update, :destroy]
      resource :roster, :only => [:show, :new, :create, :edit, :update], :controller => "game_players"
      resources :game_goalies, :only => [:new, :create]
      resource :game_officials, :only => [:edit, :update]
      resource :game_staff_members, :only => [:new, :create, :edit, :update]
      member do
        post :activate
        post :start
        post :pause
        post :finish
        post :complete
        post :sync
        put :update_clock
        put :set_mvp
      end
    end
  end

  resources :locations, :except => [:destroy] do
    resource :scoreboard, :only => :show, :controller => "locations/scoreboards"
  end

  resources :players, :only => [:show, :edit, :update, :destroy] do
    resources :claims, :only => [:show, :new, :create], :controller => "players/claims" do
      member do
        post :approve
        post :deny
      end
    end
  end

  resources :search, :only => :index, :controller => "search_results"

  resources :shared_links, :only => [:new, :create]

  resources :teams, :only => [:index, :show, :edit, :update, :destroy], :controller => "leagues/teams" do
    resources :players, :only => [:new, :create]
    resources :staff_members
  end

  resources :leagues do
    resources :teams, :only => [:new, :create], :controller => "leagues/teams"
    resources :games, :only => [:new, :create, :edit, :update, :destroy], :controller => "leagues/games"
    resources :officials, :controller => "leagues/officials"
  end

  resources :invitations, :only => [:new, :create] do
    member do
      get :accept
      get :decline
    end
  end

  resources :system_names, :only => [:show]

  resources :team_claims, :only => [:create, :show] do
    resources :players, :only => [:edit, :update], :controller => "team_claims/players"
  end

  resources :tournaments do
    resources :games, :controller => "tournaments/games"
    resources :officials, :controller => "tournaments/officials"
    resource :teams, :only => [:edit, :update], :controller => "tournaments/teams"
  end

  devise_for :users, :controllers => {:registrations => "users/registrations" }

  resources :users, :only => [:show, :edit, :update] do
    member do
      get :impersonate
    end
    collection do
      post :system_name_available
      post :email_available
    end
  end

  resources :videos, :only => [:show]

  match 'typeahead/get_users' => 'typeahead#get_users'

  namespace :admin do
    resource :kiosk, :except => [:edit, :update]
  end

  root :to => 'home#index'
  get 'about' => 'home#about'
  get 'terms' => 'home#terms'
  get 'privacy' => 'home#privacy'
  get 'press' => 'home#press'
  get 'contact' => 'home#contact'
  get 'account_created' => 'home#account_created'
  get 'popular' => "home#popular"

  get 'unsubscribe/:user_id/:token/:category' => 'unsubscribe#unsubscribe'

  match '/404', :to => 'errors#not_found'
  match '/422', :to => 'errors#server_error'
  match '/500', :to => 'errors#server_error'

  if Rails.env.development?
    mount MailPreview => 'mail_view'
  end
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  load_and_authorize_resource

  def show
    respond_to do |format|
      format.html
      format.pdf do
        send_data Gamesheets::HockeyQuebec.new(game: @game).to_pdf,
          filename: "game-#{@game.id}.pdf", type: "application/pdf", disposition: "inline"
      end
    end
  end

  def update
    respond_to do |format|
      if @game.update_attributes(params[:game])
        format.html { redirect_to @game, notice: t("controllers.games.update.success") }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/leagues/games_controller.rb
class Leagues::GamesController < ApplicationController
  load_and_authorize_resource :league, :only => [:new, :create, :edit, :update]
  load_and_authorize_resource :except => [:new, :create]

  def new
    @game = @league.games.build
    authorize! :new, @game
  end

  def create
    @game = @league.games.build(params[:game].merge(:updater => current_user))
    authorize! :create, @game

    respond_to do |format|
      if @game.save
        format.html { redirect_to league_path(@league), notice: t("controllers.leagues.games.create.success") }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @game.update_attributes(params[:game].merge(:updater => current_user))
        format.html { redirect_to @league, notice: t("controllers.leagues.games.update.success") }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    respond_to do |format|
      @game.updater = current_user
      if @game.cancel
        format.html { redirect_to :back, notice: t("controllers.leagues.games.destroy.success") }
        format.json { head :no_content }
      else
        format.html { redirect_to :back, alert: t("controllers.leagues.games.destroy.failure") }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end
end

app/controllers/marker/game_goalies_controller.rb
class Marker::GameGoaliesController < ApplicationController
  load_and_authorize_resource :game
  before_filter :load_team

  def new
    @game_goalie = @game.game_goalies.build
    authorize! :create, @game_goalie
    render :layout => !request.xhr?
  end

  def create
    @game_goalie = @game.game_goalies.build(params[:game_goalie])
    authorize! :create, @game_goalie

    if @game_goalie.goalie_id == 0
      @game.game_goalies.for_team(@team).current.readonly(false).each {|gg| gg.finish! }
      respond_to do |format|
        format.html { redirect_to @game, notice: t("controllers.marker.game_goalies.pulled") }
        format.json { head :no_content }
      end
    else
      respond_to do |format|
        if @game_goalie.save
          format.html { redirect_to @game, notice: t("controllers.marker.game_goalies.changed") }
          format.json { render json: @game, status: :created, location: @game }
        else
          format.html { render action: "new" }
          format.json { render json: @game_goalie.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  private

  def load_team
    @team = params[:team] == "visiting" ? @game.visiting_team : @game.home_team
  end
end

app/controllers/marker/game_officials_controller.rb
class Marker::GameOfficialsController < ApplicationController
  load_and_authorize_resource :game
  before_filter :load_game_officials

  def edit
    authorize! :edit, GameOfficial.new(:game => @game)
  end

  def update
    authorize! :edit, GameOfficial.new(:game => @game)

    respond_to do |format|
      begin
        if @game.update_attributes(params[:game])
          format.html { redirect_to marker_game_path(@game), notice: t("controllers.marker.game_officials.update.success") }
          format.json { head :no_content }
        else
          format.html { render action: "edit" }
          format.json { render json: @game.errors, status: :unprocessable_entity }
        end
      rescue ActiveRecord::RecordInvalid => e
        @game.errors.add(:base, t("controllers.marker.game_officials.update.failure") )
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  def load_game_officials
    @game_officials = @game.possible_officials.map {|o| [o.name, o.id] }
  end
end

app/controllers/marker/game_players_controller.rb
class Marker::GamePlayersController < ApplicationController
  load_and_authorize_resource :game
  before_filter :load_home_or_visiting
  before_filter :load_team

  # There's probably a better pattern than what we're doing here.
  # #new and #create support the creation of new players. #edit and #update manage
  # the game roster.

  def show
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @players }
    end
  end

  def new
    @player = Player.new
  end

  def create
    @player = Player.new(params[:player].merge(:team => @team))

    respond_to do |format|
      if @player.save && @game.players << @player
        format.html { redirect_to edit_marker_game_roster_path(@game, :team => @home_or_visiting), notice: t("controllers.marker.game_players.create.success") }
        format.json { render json: @game, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
    render :layout => false if request.xhr?
  end

  def update
    respond_to do |format|
      if @game.update_attributes(fix_params[:game])
        format.html { redirect_to marker_game_path(@game), notice: t("controllers.marker.game_players.update.success") }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def fix_params
    return params unless params[:game] && params[:game][:game_players_attributes]
    # First, get rid of entries for which we haven't persisted anything and which haven't been selected
    params[:game][:game_players_attributes].delete_if { |k, v| !v[:id] && !v[:selected] }

    # Then, add the "_destroy" directive to anything that remains and is unselected
    params[:game][:game_players_attributes].each do |k, v|
      v[:_destroy] = true unless v[:selected]
      v.delete(:selected)
    end

    # Leave untouched anything that is selected -- they'll be created or updated as appropriate
    params
  end

  def load_home_or_visiting
    @home_or_visiting = params[:team] == "visiting" ? "visiting" : "home"
  end

  def load_team
    @team = @game.send("#{@home_or_visiting}_team")
    @other_team = @game.opposing_team(@team)
  end
end

app/controllers/marker/game_staff_members_controller.rb
class Marker::GameStaffMembersController < ApplicationController
  load_and_authorize_resource :game
  before_filter :load_home_or_visiting
  before_filter :load_team
  before_filter :load_and_authorize_staff_member, :only => [:new, :create]
  before_filter :authorize_game_staff_member, :only => [:edit, :update]

  def new
  end

  def create
    game_staff_member = @game.game_staff_members.build(:role => @staff_member.role, :staff_member => @staff_member)
    respond_to do |format|
      if game_staff_member.save
        format.html { redirect_to marker_game_path(@game), notice: t("controllers.marker.game_staff_members.create.success") }
        format.json { render json: @staff_member, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @staff_member.errors, status: :unprocessable_entity }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @game.update_attributes(fix_params[:game])
        format.html { redirect_to marker_game_path(@game), notice: t("controllers.marker.game_staff_members.update.success") }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def authorize_game_staff_member
    authorize! :create, GameStaffMember.new(:game => @game)
  end

  def load_and_authorize_staff_member
    @staff_member = @team.staff_members.build(params[:staff_member])
    authorize! :create, @staff_member
  end

  def fix_params
    return params unless params[:game] && params[:game][:game_staff_members_attributes]
    # First, get rid of entries for which we haven't persisted anything and which haven't been selected
    params[:game][:game_staff_members_attributes].delete_if { |k, v| !v[:id] && !v[:selected] }

    # Then, add the "_destroy" directive to anything that remains and is unselected
    params[:game][:game_staff_members_attributes].each do |k, v|
      v[:_destroy] = true unless v[:selected]
      v.delete(:selected)
    end

    # Leave untouched anything that is selected -- they'll be created or updated as appropriate
    params
  end

  def load_home_or_visiting
    @home_or_visiting = params[:team] == "visiting" ? "visiting" : "home"
  end

  def load_team
    @team = @game.send("#{@home_or_visiting}_team")
    @other_team = @game.opposing_team(@team)
  end
end

app/controllers/marker/goals_controller.rb
class Marker::GoalsController < ApplicationController
  load_and_authorize_resource :game
  load_and_authorize_resource :except => [:new, :create]

  def index
  end

  def new
    @goal = @game.goals.build
    authorize! :new, @goal
  end

  def create
    @goal = @game.goals.build(params[:goal].merge(:creator => current_user))
    authorize! :create, @goal

    respond_to do |format|
      if @goal.save
        format.html { redirect_to @game, notice: 'Goal was successfully created.' }
        format.json { render json: @goal, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @goal.update_attributes(params[:goal])
        format.html { redirect_to @game, notice: 'Goal was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @goal.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @goal.updater = current_user
    @goal.destroy

    respond_to do |format|
      format.html { redirect_to @game, notice: 'Goal was removed.' }
      format.json { head :no_content }
    end
  end
end

app/controllers/marker/penalties_controller.rb
class Marker::PenaltiesController < ApplicationController
  load_and_authorize_resource :game
  load_and_authorize_resource :except => [:create]

  def create
    attrs = params[:penalty] || {}
    attrs[:game] = @game
    attrs[:period] ||= @game.period
    attrs[:elapsed_time] ||= @game.elapsed_time
    @penalty = Penalty.new(attrs)
    authorize! :create, @penalty

    respond_to do |format|
      if @penalty.save
        format.html { redirect_to @game, notice: 'Penalty was successfully created.' }
        format.json { render json: @penalty, status: :created, location: @game }
      else
        format.html { render action: "new" }
        format.json { render json: @penalty.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @penalty.update_attributes(params[:penalty].slice(*Penalty.accessible_attributes))
        format.html { redirect_to @game, notice: 'Penalty was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @penalty.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @penalty.destroy

    respond_to do |format|
      format.html { redirect_to @game, notice: 'Penalty was removed.' }
      format.json { head :no_content }
    end
  end
end

app/helpers/games_helper.rb
module GamesHelper
  def checklist_item(method, text, link)
    if @game.send(method)
      "<li><i class='icon-check text-success'></i> #{ link_to text, link }".html_safe
    else
      "<li><span class='text-error' style='margin-left: 0px; margin-right: 2px;'>&#10006;</span> <b>#{ link_to text, link }</b>".html_safe
    end
  end

  def edit_game_path(game)
    if game.nil? || game.league.nil?
      nil
    elsif game.league.is_a?(Tournament)
      edit_tournament_game_path(game.league, game)
    else
      edit_league_game_path(game.league, game)
    end
  end
end

app/views/marker/games/_game_officials.html.erb
<h2>Game Officials <%= link_to "Change", edit_game_game_officials_path(@game), :class => "btn btn-default btn-sm" %></h2>

<% if @game.game_officials.any? %>
  <dl class="dl-horizontal">
    <% @game.game_officials.each do |game_official| %>
      <dt><%= game_official.role.to_s.humanize %></dt>
      <dd><%= game_official.official.name %></dd>
    <% end %>
  </dl>
<% else %>
  <p><em>No officials have been selected. Click <b>Change</b> above to select.</em></p>
<% end %>

app/views/marker/games/_game_staff.html.erb
<% team = @game.send("#{home_or_visiting}_team") %>
<h3>Checked in for <%= team.name %></h3>

<% game_staff_members = @game.game_staff_members.for_team(team).sort_by {|gsm| StaffMember::Roles.index(gsm.role) } %>

<% if game_staff_members.any? %>
  <dl class="dl-horizontal">
    <% game_staff_members.each do |game_staff| %>
      <dt><%= game_staff.role.to_s.humanize %></dt>
      <dd><%= game_staff.staff_member.name %></dd>
    <% end %>
  </dl>
<% else %>
  <p><em>None</em></p>
<% end %>

<%= link_to "Edit", edit_game_game_staff_members_path(@game, :team => home_or_visiting),
  :class => "btn btn-default" %>

app/views/marker/games/_marker_checklist.html.erb
<div class="well">
  <ul class="unstyled">
    <%= checklist_item(:officials_checked_in?, "Check-in Game Officials", edit_marker_game_game_officials_path(@game)) %>
    <%= checklist_item(:home_team_players_checked_in?, "Check-in players for #{@game.home_team.name}", edit_marker_game_roster_path(@game, :team => :home)) %>
    <%= checklist_item(:home_team_staff_checked_in?, "Check-in staff for #{@game.home_team.name}", edit_marker_game_game_staff_members_path(@game, :team => :home)) %>
    <%= checklist_item(:visiting_team_players_checked_in?, "Check-in players for #{@game.visiting_team.name}", edit_marker_game_roster_path(@game, :team => :visiting)) %>
    <%= checklist_item(:visiting_team_staff_checked_in?, "Check-in staff for #{@game.visiting_team.name}", edit_marker_game_game_staff_members_path(@game, :team => :visiting)) %>
  </ul>

  <% if @game.ready_to_activate? %>
    <p>The checklist items above all appear to be complete! To activate the game, press the button below.</p>
  <% else %>
    <p>Please complete the remaining items above to activate the game.</p>
  <% end %>

  <div class="actions">
    <%= link_to "Cancel Game", game_path(@game), :class => "btn btn-danger", :method => :delete, :confirm => "Do you want to cancel this game?" %>
    <%= link_to "Activate Game", activate_marker_game_path(@game), :class => "btn btn-primary", :method => :post if @game.ready_to_activate? %>
  </div>
</div>

app/views/marker/games/_score_board.html.erb
<% score_board = game.score_board %>

<table class="table" style="width: 640px;">
  <tr>
    <th>Team</th>
    <th>1</th>
    <th>2</th>
    <th>3</th>
    <th>OT</th>
    <th>Total</th>
  </tr>

  <% game.teams.each do |team| %>
    <tr>
      <td><%= link_to team.name, team %></td>
      <% (Game::Periods + [:total]).each_with_index do |period, index| %>
        <td <%= "style='font-weight: bold;'".html_safe if period == :total %>><%= score_board[team.name][index] %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/marker/games/_team_box.html.erb
<div id=<%= "#{home_or_visiting}-team" %> class="team-box col-md-6">
  <div class="well well-large">
    <h3>
      <%= cl_image_tag team.logo_url(:small), :alt => "team logo", :style => "float: left; margin-right: 10px; margin-bottom: 10px;" %>
      <span class="team-name"><%= team.name %></span>
      <span class="score pull-right"></span>
    </h3>

    <% if can? :mark, @game %>
      <a href="#" class="btn btn-default add-goal" title-"Add Goal"><i class="icon-plus"></i></a>
      <a href="#" class="btn btn-default edit-roster" title="Edit Team Roster" ><i class="icon-male"></i></a>
      <a href="#" class="btn btn-default choose-goalie" title="Choose Goalie"><%= image_tag("goalie.svg", :style => "width: 16px; height: 18px;") %></a>
      <a href="#" class="btn btn-default swap" title="Switch Home/Visiting Positions"><i class="icon-refresh"></i></a>

      <span class="goalie pull-right"></span>

      <div data-remote="<%= new_marker_game_game_goalie_path(@game, :team => home_or_visiting) %>" class="goalie-chooser modal" data-backdrop="static" tabindex="-1">
        <div class="modal-content">
          <div class="modal-header"><h3>Choose goalie for <%= team.name %></h3></div>
          <div class="modal-body"></div>
          <div class="modal-footer">
            <%= link_to "Cancel", "#", :class => "cancel" %>
            <%= link_to "Save", "#", :class => "save btn btn-primary" %>
          </div>
        </div>
      </div>

      <div data-remote="<%= edit_marker_game_roster_path(@game, :team => home_or_visiting) %>" class="roster modal" data-backdrop="static" tabindex="-1">
        <div class="modal-content">
          <div class="modal-header"><h3>Select players for <%= team.name %></h3></div>
          <div class="modal-body"></div>
          <div class="modal-footer">
            <%= link_to "New Player", "#", :class => "create btn btn-default pull-left" %>
            <%= link_to "Cancel", "#", :class => "cancel" %>
            <%= link_to "Save", "#", :class => "save btn btn-primary" %>
          </div>
        </div>
      </div>

      <div data-remote="<%= new_team_player_path(team) %>" class="player modal" data-backdrop="static" tabindex="-1">
        <div class="modal-content">
          <div class="modal-header"><h3>Create new player for <%= team.name %></h3></div>
          <div class="modal-body"></div>
          <div class="modal-footer">
            <%= link_to "Cancel", "#", :class => "cancel" %>
            <%= link_to "Create", "#", :class => "create btn btn-primary" %>
          </div>
        </div>
      </div>

      <div class="goal-editor modal" data-backdrop="static" tabindex="-1">
        <div class="modal-content">
          <div class="modal-header"><h3>Goal for <%= team.name %></h3></div>
          <div class="modal-body">
            <div class="goal-advantage">
              <select><%= options_for_select(Hash[Goal::Advantages.map {|k,v| [k, t("activerecord.values.goal.advantage.#{v}")] }].invert) %></select>
            </div>

            <div class="players">

              <% { "goal-player" => "Player", "goal-assist" => "Assist 1", "goal-secondary-assist" => "Assist 2" }.each do |cls, label| %>
                <fieldset class="<%= cls %>">
                  <legend>
                    <%= label %><span class="name"></span>
                    <button class="btn btn-default btn-sm pull-right edit">Edit</button>
                    <button class="btn btn-default btn-sm pull-right clear">Clear</button>
                  </legend>
                  <div></div>
                </fieldset>
              <% end %>
            </div>
          </div>

          <div class="modal-footer">
            <%= link_to "Cancel", "#", :class => "cancel" %>
            <%= link_to "Save", "#", :class => "save btn btn-primary" %>
          </div>
        </div>
      </div>

    <% end %>

    <div class="clearfix"></div>

    <div class="tabbable penalties">
      <ul class="nav nav-tabs">
        <li><a href="#penalties-<%= home_or_visiting %>-all" data-toggle="tab"><%= t "penalties.labels.all" %> <span class="badge badge-info count"><span></a></li>
        <li><a href="#penalties-<%= home_or_visiting %>-current" class="current" data-toggle="tab"><%= t "penalties.labels.current" %> <span class="badge badge-info count"></span></a></li>
        <li><a href="#penalties-<%= home_or_visiting %>-expired" data-toggle="tab"><%= t "penalties.labels.completed" %> <span class="badge badge-info count"></span></a></li>
        <li><a href="#penalties-<%= home_or_visiting %>-other" data-toggle="tab"><%= t "penalties.labels.other"%> <span class="badge badge-info count"></span></a></li>
      </ul>

      <div class="tab-content">

        <% ["all", "current", "expired", "other"].each do |category| %>

          <div class="tab-pane fade <%= category == "all" ? "active in" : "" %>" id="<%= "penalties-#{home_or_visiting}-#{category}" %>">
            <table class="penalties table <%= category %>">
              <thead>
                <tr>
                  <th>P</th>
                  <th>Time</th>
                  <th>Plyr</th>
                  <th>Infraction</th>
                  <th></th>
                </tr>
              </thead>
              <tbody></tbody>
            </table>
          </div>
        <% end %>
      </div>
    </div>

    <h3 class="disclosure"><i></i> Goals</h3>
    <div style="display: none;">
      <table class="goals table">
        <thead>
          <tr>
            <th>Period</th>
            <th>Time</th>
            <th>Players</th>
          </tr>
        </thead>
        <tbody></tbody>
      </table>
    </div>
  </div>

</div>